(() => {
  'use strict';
  const sourceSnapshotDate = '2026-09-23';
  const evidenceWindow = '30 matched historical/replay tests on 23 September 2026';
  const nodeGraph = [
    [{x:18,y:37,kind:'MATCH',label:'same set',mark:'M'},{x:50,y:22,kind:'MIX',label:'any outcomes',mark:'?'},{x:82,y:37,kind:'BLIND',label:'ignore records',mark:'×'}],
    [{x:18,y:42,kind:'HEADLINE',label:'larger total',mark:'H'},{x:50,y:20,kind:'LEDGER',label:'closed rotations',mark:'L'},{x:82,y:42,kind:'NEW',label:'current record',mark:'N'}],
    [{x:18,y:35,kind:'ERASE',label:'remove results',mark:'×'},{x:50,y:19,kind:'DRAMA',label:'one dramatic',mark:'!'},{x:82,y:35,kind:'COUNTER',label:'8 + 1 tie',mark:'C'}],
    [{x:18,y:40,kind:'FORECAST',label:'will remain',mark:'F'},{x:50,y:18,kind:'DATED',label:'dated sample',mark:'D'},{x:82,y:40,kind:'SELECT',label:'select now',mark:'S'}]
  ];
  const scenario = { id:'HSRC-001', title:'The Split Route', graceSeconds:90, steps:[
    {title:'Set the evidence boundary',prompt:'Start with the evidence rule that makes the comparison fair.',context:'What would make a claim about Split versus Total meaningful? Both modes must be tested on the same selected strategy basket.',correct:0,options:[['Use the same basket in both modes','WHY: a matched basket removes the selection mismatch. Now any observed difference can be inspected fairly.','+30'],['Compare any attractive outcomes','WHY NOT: the results could differ only because different items were picked.','−20'],['Ignore the selected records','WHY NOT: without the record list, the comparison cannot be reproduced.','−20']]},
    {title:'Inspect what created the result',prompt:'Choose the evidence that tests whether a headline hides activity.',context:'A larger aggregate can be true but incomplete. Which record shows how the result was produced?',correct:1,options:[['Read only the larger aggregate','WHY NOT: this reports the outcome without checking the route that created it.','−20'],['Open the closed-rotation ledger','WHY: the ledger shows activity in each mode, so the observed difference has context.','+30'],['Pull a current-date record','WHY NOT: it is outside the frozen historical case and cannot explain this result.','−20']]},
    {title:'Test the claim against contrary evidence',prompt:'Keep the record that prevents an overconfident conclusion.',context:'The claim is not “Split always won.” Which evidence must remain in the reconstruction?',correct:2,options:[['Remove every contrary result','WHY NOT: hiding contrary observations turns a reconstruction into a story.','−20'],['Keep only the dramatic record','WHY NOT: one striking observation does not show the full challenge to the claim.','−20'],['Keep 8 Total-higher tests and 1 tie','WHY: this shows the result was not unanimous and keeps the conclusion honest.','+30']]},
    {title:'Reach the reveal',prompt:'Choose the statement the dated evidence can actually support.',context:'You now know the fixed sample, its route and the counter-evidence. What is the correct bounded conclusion?',correct:1,options:[['This mode will remain superior','WHY NOT: a historical sample cannot establish a future result.','−20'],['Split was higher more often in this dated sample','WHY: it says exactly what the completed evidence shows—and nothing more.','+30'],['Players should select the mode now','WHY NOT: the case does not give a current instruction or recommendation.','−20']]}
  ]};
  const state = {index:0,gamePoints:0,streak:0,elapsedSeconds:0,paused:false,choices:[],completion:false,timer:null,player:{x:50,y:83}};
  const $ = id => document.getElementById(id);
  const format = total => `${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;
  const save = () => localStorage.setItem('hsrc-001', JSON.stringify({...state,timer:null}));
  const reset = () => {clearInterval(state.timer);Object.assign(state,{index:0,gamePoints:0,streak:0,elapsedSeconds:0,paused:false,choices:[],completion:false,timer:null,player:{x:50,y:83}});localStorage.removeItem('hsrc-001');};
  const movePlayer = node => {state.player={x:node.x,y:node.y};const token=$('playerToken');token.style.setProperty('--x',`${node.x}%`);token.style.setProperty('--y',`${node.y}%`);};
  const renderChoices = step => {$('choiceGrid').replaceChildren(...step.options.map((item,i)=>{const node=nodeGraph[state.index][i];const button=document.createElement('button');button.className='map-node';button.style.setProperty('--x',`${node.x}%`);button.style.setProperty('--y',`${node.y}%`);button.innerHTML=`<span class="node-mark">${node.mark}</span><span>${node.kind}</span><small>${node.label}</small>`;button.setAttribute('aria-label',item[0]);button.onclick=()=>choose(i);return button;}));};
  const render = () => {const step=scenario.steps[state.index];if(!step){complete();return;}$('points').textContent=state.gamePoints;$('timer').textContent=format(state.elapsedSeconds);$('streak').textContent=state.streak;$('step').textContent=`${state.index+1} / ${scenario.steps.length}`;$('mapTitle').textContent=step.title;$('prompt').textContent=step.prompt;$('context').textContent=step.context;$('missionBadge').textContent=state.streak>=2?'STREAK ACTIVE':'CHOOSE A PATH';$('feedback').textContent='';$('feedback').className='feedback';$('continueGame').hidden=true;$('sourceLabel').textContent=`FROZEN CASE FILE · ${sourceSnapshotDate} · ${evidenceWindow} · GAME POINTS ONLY`;renderChoices(step);movePlayer(state.player);};
  const tick = () => {if(!state.paused&&!state.completion){state.elapsedSeconds+=1;$('timer').textContent=format(state.elapsedSeconds);save();}};
  const choose = selected => {const step=scenario.steps[state.index];const node=nodeGraph[state.index][selected];const correct=selected===step.correct;const delta=correct?30:-20;state.streak=correct?state.streak+1:0;state.gamePoints+=delta;state.choices.push({junction:step.title,selected:step.options[selected][0],correct,delta,explanation:step.options[selected][1],at:state.elapsedSeconds,node:node.kind});[...$('choiceGrid').children].forEach(button=>button.disabled=true);movePlayer(node);$('points').textContent=state.gamePoints;$('streak').textContent=state.streak;$('missionBadge').textContent=correct?'PATH SECURED':'WRONG TURN';$('feedback').textContent=step.options[selected][1];$('feedback').className=`feedback ${correct?'good':'bad'}`;$('continueGame').textContent=state.index===scenario.steps.length-1?'SEE CASE RESULT →':'NEXT JUNCTION →';$('continueGame').hidden=false;save();};
  const complete = () => {state.completion=true;clearInterval(state.timer);const penalty=Math.max(0,state.elapsedSeconds-scenario.graceSeconds);state.gamePoints-=penalty;$('game').hidden=true;$('result').hidden=false;$('resultTitle').textContent=state.gamePoints>=80?'You found the defensible route':'Case closed — inspect the wrong turns';$('resultCopy').textContent=state.gamePoints>=80?'You kept the evidence boundary, inspected the route and carried counter-evidence to the reveal.':'Your replay identifies the junctions where the reconstruction weakened.';$('finalPoints').textContent=state.gamePoints;$('finalTime').textContent=format(state.elapsedSeconds);$('routeScore').textContent=`${state.choices.filter(x=>x.correct).length} / ${scenario.steps.length}`;save();};
  const replay = () => {$('replayPanel').hidden=false;$('replaySteps').innerHTML=state.choices.map((choice,i)=>`<article class="replay-step ${choice.correct?'good':'bad'}"><small>MOVE ${i+1} · ${choice.node} · ${format(choice.at)}</small><b>${choice.selected}</b><p>${choice.delta>0?'+':''}${choice.delta} points — ${choice.explanation}</p></article>`).join('');$('replayPanel').scrollIntoView({behavior:'smooth'});};
  $('startGame').onclick=()=>{reset();$('intro').hidden=true;$('game').hidden=false;state.timer=setInterval(tick,1000);render();};
  $('continueGame').onclick=()=>{state.index+=1;render();};
  $('pauseGame').onclick=()=>{state.paused=!state.paused;$('pauseGame').textContent=state.paused?'▶':'Ⅱ';$('missionBadge').textContent=state.paused?'PAUSED':'CHOOSE A PATH';save();};
  $('restartGame').onclick=()=>{reset();$('result').hidden=true;$('replayPanel').hidden=true;$('intro').hidden=false;};
  $('replayGame').onclick=replay;
})();
