CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS subscribers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    confirmation_token VARCHAR(100) UNIQUE,
    confirmed_at TIMESTAMP,
    unsubscribe_token VARCHAR(100) UNIQUE,
    unsubscribed_at TIMESTAMP,
    preferences JSONB,
    source_tag VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriber_lifecycle_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscriber_id INTEGER NOT NULL REFERENCES subscribers(id) ON DELETE CASCADE,
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(50) NOT NULL,
    event_metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS content_queue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id UUID NOT NULL DEFAULT gen_random_uuid(),
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    content_data JSONB NOT NULL,
    scheduled_for TIMESTAMP NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    max_retries INTEGER NOT NULL DEFAULT 3,
    last_error VARCHAR(500),
    next_retry_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS content_variants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_item_id INTEGER NOT NULL REFERENCES content_queue(id) ON DELETE CASCADE,
    platform VARCHAR(50) NOT NULL,
    headline VARCHAR(300) NOT NULL,
    body TEXT NOT NULL,
    hashtags JSONB,
    call_to_action VARCHAR(255) NOT NULL,
    variant_metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_content_variants_queue_platform UNIQUE (queue_item_id, platform)
);

CREATE TABLE IF NOT EXISTS conversion_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    session_id VARCHAR(100),
    url VARCHAR(500),
    utm_source VARCHAR(100),
    utm_medium VARCHAR(100),
    utm_campaign VARCHAR(100),
    utm_content VARCHAR(100),
    utm_term VARCHAR(100),
    subscriber_id INTEGER REFERENCES subscribers(id),
    event_metadata JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagement_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_item_id INTEGER NOT NULL REFERENCES content_queue(id) ON DELETE CASCADE,
    platform VARCHAR(50) NOT NULL,
    metric_date DATE NOT NULL,
    impressions INTEGER NOT NULL DEFAULT 0,
    reactions INTEGER NOT NULL DEFAULT 0,
    comments INTEGER NOT NULL DEFAULT 0,
    shares INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    saves INTEGER NOT NULL DEFAULT 0,
    watch_seconds INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_engagement_metrics_queue_platform_day UNIQUE (queue_item_id, platform, metric_date)
);

CREATE TABLE IF NOT EXISTS account_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform VARCHAR(50) NOT NULL,
    metric_date DATE NOT NULL,
    follower_count INTEGER NOT NULL DEFAULT 0,
    reach INTEGER NOT NULL DEFAULT 0,
    profile_views INTEGER NOT NULL DEFAULT 0,
    subscriber_count INTEGER NOT NULL DEFAULT 0,
    conversion_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_account_metrics_platform_day UNIQUE (platform, metric_date)
);

CREATE TABLE IF NOT EXISTS manual_controls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(64) NOT NULL,
    is_paused BOOLEAN NOT NULL DEFAULT FALSE,
    emergency_stop_active BOOLEAN NOT NULL DEFAULT FALSE,
    emergency_mode VARCHAR(32),
    reason VARCHAR(500),
    updated_by VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_manual_controls_scope UNIQUE (scope_type, scope_key)
);

CREATE TABLE IF NOT EXISTS intervention_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(64) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    scope_key VARCHAR(64) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    reason VARCHAR(500),
    target_queue_id INTEGER,
    metadata TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_subscribers_email ON subscribers(email);
CREATE INDEX IF NOT EXISTS ix_subscribers_status ON subscribers(status);
CREATE INDEX IF NOT EXISTS ix_subscriber_lifecycle_events_subscriber_id ON subscriber_lifecycle_events(subscriber_id);
CREATE INDEX IF NOT EXISTS ix_subscriber_lifecycle_events_event_type ON subscriber_lifecycle_events(event_type);
CREATE INDEX IF NOT EXISTS ix_content_queue_platform ON content_queue(platform);
CREATE INDEX IF NOT EXISTS ix_content_queue_status ON content_queue(status);
CREATE INDEX IF NOT EXISTS ix_content_queue_scheduled_for ON content_queue(scheduled_for);
CREATE INDEX IF NOT EXISTS ix_content_variants_queue_item_id ON content_variants(queue_item_id);
CREATE INDEX IF NOT EXISTS ix_conversion_events_event_type ON conversion_events(event_type);
CREATE INDEX IF NOT EXISTS ix_conversion_events_utm_source ON conversion_events(utm_source);
CREATE INDEX IF NOT EXISTS ix_engagement_metrics_metric_date ON engagement_metrics(metric_date);
CREATE INDEX IF NOT EXISTS ix_account_metrics_metric_date ON account_metrics(metric_date);

DROP VIEW IF EXISTS subscriber_growth_snapshot;
CREATE VIEW subscriber_growth_snapshot AS
SELECT
    DATE(s.created_at) AS snapshot_date,
    COUNT(*) AS total_subscribers,
    SUM(CASE WHEN s.status = 'confirmed' THEN 1 ELSE 0 END) AS confirmed_subscribers,
    SUM(CASE WHEN s.status = 'pending' THEN 1 ELSE 0 END) AS pending_subscribers,
    SUM(CASE WHEN s.status = 'unsubscribed' THEN 1 ELSE 0 END) AS unsubscribed_subscribers
FROM subscribers s
GROUP BY DATE(s.created_at);

DROP VIEW IF EXISTS content_performance_snapshot;
CREATE VIEW content_performance_snapshot AS
SELECT
    cq.platform,
    em.metric_date,
    COUNT(DISTINCT cq.id) AS queued_posts,
    COALESCE(SUM(em.impressions), 0) AS total_impressions,
    COALESCE(SUM(em.clicks), 0) AS total_clicks,
    COALESCE(SUM(em.comments), 0) AS total_comments,
    COALESCE(SUM(em.shares), 0) AS total_shares,
    COALESCE(SUM(em.reactions), 0) AS total_reactions
FROM content_queue cq
LEFT JOIN engagement_metrics em ON em.queue_item_id = cq.id
GROUP BY cq.platform, em.metric_date;
