import { ClientItem, InboxItem, Tone } from './types';

export const INBOX_FILTERS = [
  { key: 'all', label: 'All' },
  { key: 'needs_review', label: 'Needs Review' },
  { key: 'financial', label: 'Financial' },
  { key: 'quotes', label: 'Quotes' },
  { key: 'payments', label: 'Payments' },
  { key: 'alerts', label: 'Alerts' },
] as const;

export const FINANCIAL_ENTITY_TYPES = new Set(['invoice', 'receipt', 'receipt_expense', 'payment', 'quote', 'booking', 'note']);

export const TONE_STYLES: Record<Tone, { backgroundColor: string; color: string }> = {
  warning: { backgroundColor: '#fff1c2', color: '#8a5a00' },
  success: { backgroundColor: '#d9f7e8', color: '#0f6b46' },
  info: { backgroundColor: '#dbeafe', color: '#155e75' },
  muted: { backgroundColor: '#eceff3', color: '#55606f' },
  danger: { backgroundColor: '#ffe0e0', color: '#a61b1b' },
};

export const DEMO_INBOX_ITEMS: InboxItem[] = [
  {
    event_id: 'demo-event-1',
    event_type: 'entity_status_changed',
    event_title: 'invoice overdue',
    linked_entity_id: 'demo-invoice-001',
    linked_entity_type: 'invoice',
    linked_entity: {
      id: 'demo-invoice-001',
      type: 'invoice',
      reference_number: 'INV-24031',
      status: 'overdue',
      counterparty_id: 'demo-client-001',
      counterparty_name: 'Acorn Joinery',
    },
    amount: { value: 1480, currency: 'GBP' },
    counterparty: 'Acorn Joinery',
    status_badge: { label: 'overdue', tone: 'warning' },
    timestamp: new Date().toISOString(),
    auto_commit_badge: null,
    needs_review_badge: { label: 'Needs Review', tone: 'warning' },
    description: 'Invoice is overdue and needs operator follow-up.',
    source_type: 'system',
    quarter_reference: '2026-Q1',
    filter_tags: ['all', 'needs_review', 'financial'],
  },
  {
    event_id: 'demo-event-2',
    event_type: 'payment_recorded',
    event_title: 'payment recorded from Camden Kitchen Studio',
    linked_entity_id: 'demo-payment-001',
    linked_entity_type: 'payment',
    linked_entity: {
      id: 'demo-payment-001',
      type: 'payment',
      reference_number: 'PAY-9914',
      status: 'paid',
      counterparty_id: 'demo-client-002',
      counterparty_name: 'Camden Kitchen Studio',
    },
    amount: { value: 900, currency: 'GBP' },
    counterparty: 'Camden Kitchen Studio',
    status_badge: { label: 'paid', tone: 'success' },
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    auto_commit_badge: null,
    needs_review_badge: null,
    description: 'Matched payment confirmed against the outstanding invoice.',
    source_type: 'manual',
    quarter_reference: '2026-Q1',
    filter_tags: ['all', 'financial', 'payments'],
  },
  {
    event_id: 'demo-event-3',
    event_type: 'quote_converted',
    event_title: 'quote converted to invoice',
    linked_entity_id: 'demo-quote-001',
    linked_entity_type: 'quote',
    linked_entity: {
      id: 'demo-quote-001',
      type: 'quote',
      reference_number: 'QT-7710',
      status: 'converted',
      counterparty_id: 'demo-client-003',
      counterparty_name: 'Elm Court Management',
    },
    amount: { value: 2250, currency: 'GBP' },
    counterparty: 'Elm Court Management',
    status_badge: { label: 'converted', tone: 'info' },
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    auto_commit_badge: { label: 'Auto-Commit', tone: 'warning' },
    needs_review_badge: null,
    description: 'Operator-approved quote conversion completed successfully.',
    source_type: 'voice',
    quarter_reference: '2026-Q1',
    filter_tags: ['all', 'financial', 'quotes'],
  },
  {
    event_id: 'demo-event-4',
    event_type: 'quarter_reopened',
    event_title: 'quarter reopened',
    linked_entity_id: null,
    linked_entity_type: 'quarter',
    linked_entity: {
      id: null,
      type: 'quarter',
      reference_number: '2026-Q1',
      status: 'open',
      counterparty_id: null,
      counterparty_name: null,
    },
    amount: null,
    counterparty: null,
    status_badge: { label: 'Alert', tone: 'danger' },
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    auto_commit_badge: null,
    needs_review_badge: { label: 'Needs Review', tone: 'warning' },
    description: 'Quarter reopened after a late receipt correction.',
    source_type: 'manual',
    quarter_reference: '2026-Q1',
    filter_tags: ['all', 'needs_review', 'alerts'],
  },
];

export const DEMO_CLIENTS: ClientItem[] = [
  { id: 'demo-client-001', name: 'Acorn Joinery', phone: '020 7946 0121', email: 'accounts@acornjoinery.test' },
  { id: 'demo-client-002', name: 'Camden Kitchen Studio', phone: '020 7946 0147', email: 'finance@camdenkitchen.test' },
  { id: 'demo-client-003', name: 'Elm Court Management', phone: '020 7946 0179', email: 'ops@elmcourt.test' },
];
