import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f4f7f2' },
  safeAreaDark: { backgroundColor: '#08110f' },
  container: { flex: 1, paddingHorizontal: 18, paddingTop: 18 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  logo: { fontSize: 28, fontWeight: '800', color: '#0f766e' },
  logoSub: { marginTop: 2, color: '#64748b', fontSize: 12 },
  headerIcons: { flexDirection: 'row', alignItems: 'center' },
  iconButton: { marginLeft: 14 },
  disclaimer: { color: '#7c5f12', backgroundColor: '#fff7d6', borderColor: '#f3dfa1', borderWidth: 1, borderRadius: 12, paddingVertical: 8, paddingHorizontal: 10, marginBottom: 10, fontSize: 12, fontWeight: '600' },
  scrollContainer: { flex: 1, marginBottom: 148 },
  heroCard: { backgroundColor: '#0f172a', borderRadius: 28, padding: 24, marginBottom: 18 },
  heroEyebrow: { color: '#93c5fd', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  heroAmount: { color: '#f8fafc', fontSize: 46, fontWeight: '800', marginTop: 8 },
  heroSubtitle: { color: '#cbd5e1', fontSize: 14, lineHeight: 20, marginTop: 8 },
  heroSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 18 },
  heroSummaryItem: { flex: 1 },
  heroSummaryLabel: { color: '#93c5fd', fontSize: 11, textTransform: 'uppercase', fontWeight: '700' },
  heroSummaryValue: { color: '#ffffff', fontSize: 22, fontWeight: '800', marginTop: 4 },
  noticeCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff5e6', borderRadius: 16, padding: 14, marginBottom: 14 },
  noticeCardDark: { backgroundColor: '#332211' },
  noticeText: { marginLeft: 10, flex: 1, color: '#8a5a00', fontWeight: '600', fontSize: 13 },
  gridWrap: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 18 },
  gridItem: { width: (width - 52) / 2, backgroundColor: '#ffffff', borderRadius: 22, padding: 18, marginBottom: 14 },
  gridValue: { fontSize: 26, fontWeight: '800', color: '#0f172a', marginTop: 14 },
  gridTitle: { marginTop: 6, fontSize: 15, fontWeight: '700', color: '#0f172a' },
  gridMeta: { marginTop: 4, fontSize: 12, color: '#64748b', lineHeight: 18 },
  sectionHeader: { marginBottom: 10 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: '#334155', textTransform: 'uppercase', letterSpacing: 0.8 },
  sectionMeta: { marginTop: 4, fontSize: 13, color: '#64748b', maxWidth: 260 },
  refreshChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  refreshChipDark: { backgroundColor: '#132120' },
  refreshChipText: { marginLeft: 6, fontWeight: '700', color: '#0f172a' },
  listCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 18, padding: 14, marginBottom: 10 },
  listIcon: { marginRight: 12 },
  listBody: { flex: 1 },
  listTitle: { fontSize: 14, fontWeight: '700', color: '#0f172a' },
  listMeta: { fontSize: 12, color: '#64748b', marginTop: 4, lineHeight: 17 },
  filterRow: { marginBottom: 12 },
  filterRowContent: { paddingRight: 8 },
  filterChip: { flexDirection: 'row', alignItems: 'center', borderRadius: 999, backgroundColor: '#ffffff', paddingVertical: 10, paddingHorizontal: 14, marginRight: 8 },
  filterChipDark: { backgroundColor: '#132120' },
  filterChipActive: { backgroundColor: '#0f766e' },
  filterChipText: { fontSize: 13, fontWeight: '700', color: '#0f172a' },
  filterChipTextActive: { color: '#ffffff' },
  filterCountPill: { marginLeft: 8, minWidth: 24, borderRadius: 999, backgroundColor: '#e2e8f0', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 2 },
  filterCountPillActive: { backgroundColor: 'rgba(255,255,255,0.2)' },
  filterCountText: { fontSize: 11, fontWeight: '800', color: '#0f172a' },
  filterCountTextActive: { color: '#ffffff' },
  stateCard: { backgroundColor: '#ffffff', borderRadius: 18, padding: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  stateText: { marginTop: 10, color: '#64748b', fontWeight: '600' },
  inboxCard: { backgroundColor: '#ffffff', borderRadius: 22, padding: 18, marginBottom: 12 },
  inboxCardHeader: { flexDirection: 'row', alignItems: 'center' },
  eventIconWrap: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#ecfeff', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  inboxCardTitleWrap: { flex: 1 },
  inboxTitle: { fontSize: 15, fontWeight: '800', color: '#0f172a' },
  inboxMeta: { marginTop: 4, color: '#64748b', fontSize: 12 },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, marginRight: 8, marginBottom: 8 },
  badgeText: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  inboxDetailGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
  inboxDetailItem: { width: '50%', marginTop: 10, paddingRight: 8 },
  inboxDetailLabel: { fontSize: 11, color: '#64748b', textTransform: 'uppercase', fontWeight: '700' },
  inboxDetailValue: { marginTop: 4, fontSize: 13, fontWeight: '700', color: '#0f172a' },
  inboxDescription: { marginTop: 14, color: '#475569', lineHeight: 20, fontSize: 13 },
  rankPill: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#dbeafe', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  rankPillText: { color: '#1d4ed8', fontWeight: '800' },
  scoreText: { fontSize: 15, fontWeight: '800', color: '#0f172a' },
  backRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  backText: { marginLeft: 6, color: '#64748b', fontWeight: '700' },
  entityHeroCard: { backgroundColor: '#ffffff', borderRadius: 24, padding: 22, marginBottom: 12 },
  entityEyebrow: { color: '#0f766e', fontWeight: '800', fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },
  entityTitle: { fontSize: 24, fontWeight: '800', color: '#0f172a', marginTop: 8 },
  entitySubtitle: { color: '#64748b', marginTop: 6, fontSize: 14 },
  entityHeroMeta: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 },
  entityTagRow: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  entityTag: { backgroundColor: '#e0f2fe', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, marginRight: 8, marginBottom: 8 },
  entityTagText: { color: '#075985', fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  entitySummaryCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 18, marginBottom: 12 },
  entitySummaryText: { marginTop: 12, fontSize: 14, lineHeight: 22, color: '#475569' },
  entityFieldRow: { borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 12, marginTop: 12 },
  entityFieldLabel: { fontSize: 11, fontWeight: '700', color: '#64748b', textTransform: 'uppercase' },
  entityFieldValue: { marginTop: 5, fontSize: 14, fontWeight: '700', color: '#0f172a', lineHeight: 20 },
  entityTimelineRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 14 },
  entityTimelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#0f766e', marginTop: 7, marginRight: 12 },
  entityTimelineBody: { flex: 1, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: '#e2e8f0' },
  entityTimelineMeta: { marginTop: 4, color: '#64748b', fontSize: 12, fontWeight: '600' },
  entityActionWrap: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  entityActionChip: { borderRadius: 999, backgroundColor: '#dcfce7', paddingHorizontal: 12, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
  entityActionText: { color: '#166534', fontSize: 12, fontWeight: '800' },
  bottomNav: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 84, backgroundColor: '#ffffff', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#dbe3dc', paddingBottom: 16 },
  bottomNavDark: { backgroundColor: '#0d1917', borderTopColor: '#17312d' },
  navItem: { alignItems: 'center', flex: 1 },
  navLabel: { fontSize: 10, fontWeight: '700', marginTop: 4 },
  voiceBar: { position: 'absolute', left: 18, right: 18, bottom: 94, borderRadius: 999, backgroundColor: '#ffffff', flexDirection: 'row', alignItems: 'center', padding: 10 },
  voiceBarDark: { backgroundColor: '#0d1917' },
  actionButton: { paddingHorizontal: 8 },
  input: { flex: 1, paddingHorizontal: 12, fontSize: 15, color: '#0f172a' },
  inputDark: { color: '#f8fafc' },
  micButton: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#0f766e', alignItems: 'center', justifyContent: 'center' },
  micButtonActive: { backgroundColor: '#dc2626' },
  tabTitle: { fontSize: 28, fontWeight: '800', color: '#0f172a' },
  cardDark: { backgroundColor: '#10201e' },
  textWhite: { color: '#f8fafc' },
});
